config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :dishes do
    resources :favorite_dishes, only: %i[create destroy]
  end
  resources :cooked_dishes, only: %i[index create destroy]
  resources :favorite_dishes, only: :index
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cooked_dish.rb
# frozen_string_literal: true

class CookedDish < ApplicationRecord
  belongs_to :dish
  belongs_to :user
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  has_many :cooked_dishes, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
end

app/models/favorite_dish.rb
# frozen_string_literal: true

class FavoriteDish < ApplicationRecord
  belongs_to :dish
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable, :registerable, :recoverable

  has_many :webauthn_credentials, dependent: :destroy
  has_many :dishes, dependent: :destroy
  has_many :cooked_dishes, dependent: :destroy
  has_many :favorite_dishes, dependent: :destroy

  validates :name, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/webauthn_credential.rb
# frozen_string_literal: true

class WebauthnCredential < ApplicationRecord
  belongs_to :user

  validates :external_id, presence: true, uniqueness: true
  validates :public_key, presence: true
  validates :nickname, presence: true, uniqueness: { scope: :user_id }
  validates :sign_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/cooked_dishes_controller.rb
# frozen_string_literal: true

class CookedDishesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cooked_dish, only: :destroy

  def index
    @cooked_dishes = current_user.cooked_dishes.where(cooked_at: Time.zone.today.all_month)
    @month = I18n.l Time.zone.today, format: '%B'
  end

  def create
    @cooked_dish = CookedDish.new(cooked_dish_params)
    @cooked_dish.user = current_user
    @cooked_dish.cooked_at = Time.zone.today if @cooked_dish.cooked_at.nil?

    if @cooked_dish.save
      redirect_to action: 'index'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @cooked_dish.destroy
    redirect_to action: 'index'
  end

  def set_cooked_dish
    @cooked_dish = CookedDish.find(params[:id])
  end

  def cooked_dish_params
    params.require(:cooked_dish).permit(:dish_id, :cooked_at)
  end
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dish, only: %i[show edit update destroy]

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @dishes = if params[:user_id]
                User.find(params[:user_id]).dishes
              else
                Dish.all
              end
  end

  def show; end

  def new
    @dish = Dish.new
  end

  def edit
    authorize @dish
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.user = current_user

    if @dish.save
      redirect_to action: 'index'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @dish
    if @dish.update(dish_params)
      redirect_to dish_url(@dish)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @dish
    Rails.logger.debug 'Destroying dish'
    @dish.destroy
    Rails.logger.debug 'Dish destroyed'
    redirect_to action: 'index'
  end

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :hint)
  end

  def user_not_authorized
    flash[:alert] = I18n.t('authorization.fail.dish.edit', user_name: @dish.user.name)
    redirect_back(fallback_location: dish_path(@dish))
  end
end

app/controllers/favorite_dishes_controller.rb
# frozen_string_literal: true

class FavoriteDishesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorite_dishes = current_user.favorite_dishes
  end

  def create
    dish = Dish.find(params[:dish_id])
    FavoriteDish.create(dish:, user: current_user)
    redirect_to dish_url(dish)
  end

  def destroy
    destroyed_favorite_dish = FavoriteDish.find(params[:id]).destroy
    redirect_to dish_url(destroyed_favorite_dish.dish)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:email])
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def random_dish
    random_id = Dish.pluck(:id).sample
    Dish.find(random_id) if random_id
  end

  def markdown(text)
    return if text.nil?

    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, autolink: true, no_intra_emphasis: true)
    markdown = Redcarpet::Markdown.new(renderer)

    markdown.render(text).html_safe # rubocop:disable Rails/OutputSafety
  end
end

app/views/cooked_dishes/index.html.erb
<section>
  <h1><%= I18n.t('cooked_dishes.index.random-headline') %></h1>
  <p><mark><%= random_dish.name %></mark></p>
</section>
<section>
  <h1><%= I18n.t('cooked_dishes.index.headline', month: @month) %></h1>
  <ul>
    <% @cooked_dishes.each do |cooked_dish| %>
      <li>
        <%= cooked_dish.cooked_at %>: <%= link_to cooked_dish.dish.name, dish_path(cooked_dish.dish) %>

        <%= link_to cooked_dish_path(cooked_dish), title: "hurz", data: {turbo_method: :delete } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/dishes/_cooked_today.html.erb
<%= form_with model: dish.cooked_dishes.build, scope: :cooked_dish do |form| %>
  <%= form.hidden_field :dish_id %>
  <%= form.hidden_field :cooked_at, value: Date.today %>
  <div class= "cooked-today">
    <%= form.submit I18n.t(:cooked_today) %>
  </div>
<% end %>

app/views/dishes/_favorite.html.erb
<% if favorite_dish.present? %>
  <%= link_to dish_favorite_dish_path(dish_id: dish.id, id: favorite_dish.id), title: "hurz", data: {turbo_method: :delete } do %>
    <i class="fa-solid fa-star"></i>
  <% end %>
<% else %>
  <%= link_to dish_favorite_dishes_path(dish_id: dish.id), title: "auch hurz", data: {turbo_method: :post } do %>
    <i class="fa-regular fa-star"></i>
  <% end %>
<% end %>

app/views/dishes/_form.html.erb
<%= form_with model: dish do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% dish.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :hint, title: I18n.t('dishes.form.hint.markdown') %><br>
    <%= form.text_area :hint %>
    <% dish.errors.full_messages_for(:hint).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<section>
  <h1><%= I18n.t('dishes.edit.headline') %></h1>
  <%= render "form", dish: @dish %>
</section>

app/views/dishes/index.html.erb
<% if random_dish.present? %>
  <section>
    <h1><%= I18n.t('dishes.index.random-headline') %></h1>
    <p><mark><%= random_dish.name %></mark></p>
  </section>
<% end %>
<% if @dishes.present? %>
  <section>
    <h1><%= I18n.t('dishes.index.headline') %></h1>
    <ul>
      <% @dishes.each do |dish| %>
        <li>
          <%= link_to dish.name, dish_path(dish) %>
        </li>
      <% end %>
    </ul>
  </section>
<% else %>
  <p><%= I18n.t('dishes.index.no-dishes') %></p>
<% end %>

app/views/dishes/new.html.erb
<section>
  <h1><%= I18n.t('dishes.new.headline') %></h1>
  <%= render "form", dish: @dish %>
</section>

app/views/dishes/show.html.erb
<section>
<h1><%= I18n.t('dishes.show.headline', name: @dish.name) %><%= render "favorite", favorite_dish: current_user.favorite_dishes.find_by(dish:@dish) ,dish: @dish %></h1>
<% if @dish.user != current_user %>
<p><%= I18n.t('dishes.show.attribution', name: @dish.user.name) %></p>
<% end %>
<p>
  <%= markdown(@dish.hint) %>
</p>
<div class = "grid">
  <% if @dish.user == current_user %>
  <div>
    <%= link_to I18n.t('dishes.show.edit'), edit_dish_path(@dish), role: "button", class: "outline" %>
    <%= link_to I18n.t('dishes.show.delete'), dish_path(@dish), data: {turbo_method: :delete, turbo_confirm: I18n.t('dishes.show.confirm_delete')}, role: "button", class: "outline" %>
  </div>
  <% end %>
  <div><%= render "cooked_today", dish: @dish %></div>

</div>

</section>

app/views/favorite_dishes/index.html.erb
<% if @favorite_dishes.present? %>
  <section>
    <h1><%= I18n.t('favorite_dishes.index.headline') %></h1>
    <ul>
      <% @favorite_dishes.each do |favorite_dish| %>
        <li>
          <%= link_to favorite_dish.dish.name, dish_path(favorite_dish.dish) %> <%= I18n.t('dishes.show.attribution', name: favorite_dish.dish.user.name) %>
        </li>
      <% end %>
    </ul>
  </section>
<% else %>
  <p><%= I18n.t('favorite_dishes.index.no-dishes') %></p>
<% end %>

app/views/home/index.html.erb
<% if random_dish.present? %>
  <section>
    <h1><%= I18n.t('home.index.random-headline') %></h1>
    <p><mark><%= random_dish.name %></mark></p>
  </section>
<% end %>
<section>
  <h1><%= I18n.t('home.index.headline') %></h1>
  <p>
    <%= I18n.t('home.index.description') %>
  </p>
  <p>
    <%= I18n.t('home.index.usage') %>
  </p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyDish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="<%= image_path("favicon.ico") %>" rel="shortcut icon" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class = "container">
      <nav>
        <ul>
          <li>
            <%= link_to(root_path) do%>
              <%= image_tag "logo.svg", alt: "Daily Dish Logo", width: "50", height: "50" %>
            <% end %>
          </li>
          <li><strong><%= I18n.t('navigation.headline') %></strong></li>
        </ul>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to I18n.t('navigation.links.new_dish'), new_dish_path %></li>
            <li><%= link_to I18n.t('navigation.links.all_dishes'), dishes_path %></li>
            <li><%= link_to I18n.t('navigation.links.my_dishes'), dishes_path(user_id: current_user.id) %></li>
            <li><%= link_to I18n.t('navigation.links.favorite_dishes'), favorite_dishes_path %></li>
            <li><%= link_to I18n.t('navigation.links.all_cooked_dishes'), cooked_dishes_path %></li>
            <li><%= link_to I18n.t('navigation.links.logout'), destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <% else %>
            <li><%= link_to I18n.t('navigation.links.register'), new_user_registration_path %></li>
            <li><%= link_to I18n.t('navigation.links.login'), new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <main class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>